Repository WebUI-Project-Based-10-nr/ClientMobile, pull requests merged in 2024-10, with the labels that each got.

#75 set up SonarCloud clientmobile integration
  .github/workflows/test-and-build.yml
  jest.config.js
  sonar-project.properties
Labels: React Native, feature, Sprint 1

#77 Update upload-artifact action to v4 to fix deprecated error
  .github/workflows/test-and-build.yml
  sonar-project.properties
Labels: bug, React Native, Sprint 2

#78 test for ButtonsGeneral component
  src/components/buttons-general/index.jsx
  src/tests/unit/components/buttons-general/index.test.js
Labels: test
